# Install dependencies only when needed
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy dependency files
COPY package.json package-lock.json ./
# Clean install to ensure reproducible builds
RUN npm ci

# Rebuild the source code only when needed
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Which app to build (storefront or vendor-dashboard)
ARG APP_NAME=storefront
ENV APP_NAME=${APP_NAME}

# Build the Next.js app via Nx
RUN npx nx build ${APP_NAME}

# Production image, copy all the files and run next
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
# Cloud Run defaults to 8080
ENV PORT 8080 
# Disable telemetry in CI/CD
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Which app to run
ARG APP_NAME=storefront
ENV APP_NAME=${APP_NAME}

# Copy the standalone output generated by Next.js
COPY --from=builder --chown=nextjs:nodejs /app/apps/${APP_NAME}/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/${APP_NAME}/.next/static ./apps/${APP_NAME}/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/apps/${APP_NAME}/public ./apps/${APP_NAME}/public

USER nextjs

EXPOSE 8080

# Use shell form for CMD so environment variables expand properly
CMD node apps/${APP_NAME}/server.js
