# Install dependencies only when needed
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy dependency files
COPY package.json package-lock.json ./
# Clean install to ensure reproducible builds
RUN npm ci

# Rebuild the source code only when needed
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Pass in optional build-time environment variables
# ARG NEXT_PUBLIC_API_URL
# ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

# Build the Next.js app via Nx
RUN npx nx build storefront

# Production image, copy all the files and run next
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
# Cloud Run defaults to 8080
ENV PORT 8080 
# Disable telemetry in CI/CD
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy the standalone output generated by Next.js
# Note: Next.js standalone retains the monorepo structure
# which means server.js will be inside apps/storefront/
COPY --from=builder --chown=nextjs:nodejs /app/apps/storefront/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/storefront/.next/static ./apps/storefront/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/apps/storefront/public ./apps/storefront/public

# IMPORTANT: Depending on the Nx plugin version, the standalone output might be under /dist/apps/storefront/.next/standalone instead.
# If the build fails finding the standalone folder, adjust the source paths above to start with /dist/

USER nextjs

EXPOSE 8080

CMD ["node", "apps/storefront/server.js"]
